### ISSUE TITLE
Remove Angular

### ISSUE THREAD

**Issue by NathanMarq** [NathanMarq/ng-express-scaffold#11]
Take out Angular from the repo, and abstract it out so it can be built with a NPM install.

Once this is done, provide options/user input in the bootstrap.sh to install angular, polymer, or just a index.html file.

**Comment by thomasjfox1** [comment]
This would be a nice feature!

**Comment by NathanMarq** [comment]
@thomasjfox1 Yep, the idea would be to keep the nodeserver completely separate from the static files. That way it's clear what's server-side and what's client-side. Plus, there are a lot of different app frameworks that I don't have set up, but you may want to use it with.

**Comment by NathanMarq** [comment]
Angular has been removed as of 2d2bbf2, closing this issue for now.
