### ISSUE TITLE
Add bootstrap file to help the user to install global dependencies

### ISSUE THREAD

**Issue by haoliangyu** [NathanMarq/ng-express-scaffold#15]
One drawback of using the npm scripts is that they rely on global dependencies. Please add a bootstrap file to let the user know and install the global dependencies.

PS: for development environment

**Comment by jvgriffis** [comment]
There already is a bootstrap.sh?

**Comment by haoliangyu** [comment]
I mean for the developer's own machine, not the Vagrant machine. I believe everybody is not running the `npm run xxx` in Vagrant.

**Comment by NathanMarq** [comment]
the NPM scripts don't need those dependencies to be globally installed. Installing them locally into the node_modules file should be sufficient for `npm run xxx` to work properly
