### ISSUE TITLE
ng-annotate fails if the target folder does not exist

### ISSUE THREAD

**Issue by haoliangyu** [NathanMarq/ng-express-scaffold#18]
Npm script `concat:js` needs the target folder to exist. Should add `mkdir -p public/script` somewhere as prerequisite.

**Comment by jvgriffis** [comment]
Another good reason to stop using angular. ;)

**Comment by NathanMarq** [comment]
@haoliangyu Is this folder not already in the project? The only reason it wouldn't be there is if you specifically deleted it... The `public/scripts` directory has a README in it on this repo specifically so that it already exists. (github doesn't like empty dirs)
