### ISSUE TITLE
Lockit Install Quick Fix!

### ISSUE THREAD

**Issue by thomasjfox1** [NathanMarq/ng-express-scaffold#23]
Hey! Love the new additions to the project. Was looking around and found this: 

`npm intall --save lockit`

Don't forget the `s`! 

https://github.com/NathanMarq/ng-express-scaffold/blob/master/bootstrapping/extras/install_lockit.sh

**Comment by NathanMarq** [comment]
Thanks, @thomasjfox1! I'll push up that fix with a bunch of new changes soon :)

**Comment by NathanMarq** [comment]
Fixed in commit 2d2bbf2 :)
